### ISSUE TITLE
Policies regarding project dependencies

### ISSUE THREAD

**Issue by Manu343726** [foonathan/cppast#52]
I would like to open a discussion regarding how dependencies (and especially updating dependencies) should be handled in this project.

***Please note I'm not talking about dependency managers or using a dependency manager***

After some weeks working with the lib I found myself experimenting (Suffering, actually :P) the following scenario multiple times:

 - A dependency of a cppast dependency causes an issue.
 - Fix the issue
 - Update the cppast dependency to include the dependency of dependency fix
 - Update cppast to include the latest version of its dependency

This is exacerbated by the fact git submodules are a pain to work with (I'm at a 4th level in the dependency tree, with cppast being a submodule of my project). Maybe it's just me...

Anyway, I'm here because I think most of this issues would not be so if we write down some policies regarding cppast dependencies. Some ideas/questions:

 - Should cppast master include the latest master type_safe available?
 - What about type_safe and debug_assert? Same "always-up-to-date" policy as above?

Properly versioning the library(ies) would fix this situation ("cppast v1.3 uses type_safe v0.5, which uses debug_assert v1.0", but since all the three are under active development versioning is not a complete solution (In the case of stable releases the same issues would arise during development on the active branches).
Also, this same policies would make much more clear to me how to package the libraries.

Regarding versioning, maybe you could adopt a release train strategy, where you use cppast development (And Standardese) as locomotives of the train, releasing new versions of your libs every two months or so, including all master changes since the last release. In that case, I'm sure 90% of the time the release would be something like this:

 - debug_assert: Fixes, if any. Increase fix number
 - type_safe: Fixes, if any. Increase fix number. Reference debug_assert release above. A change whose sole purpose is to update to a non-breaking fix release of debug_assert is considered a fix. Updating to debug_assert minors (Like you developed a non-breaking debug_assert feature you find interesting for type_safe) is up to you. Else is major.
 - cppast: Features and/or fixes. Increase fix or minor number. Reference type_safe above. Same policies regarding dependencies described above.

Just some ideas, I would love to hear your opinion.

Thanks in advance.

**Comment by foonathan** [comment]
What I'm currently doing is this:

I work on standardese/cppast/whatever, when I need something in a dependency, I implement it there, then update the submodule. When there is a non-critical bug (like the -Wassume) I fix it in the dependency, but don't update the submodule. When there is a breaking change in a dependency, I immediately update all that are affacted (this works because most of the dependencies are my projects).

I do it that way because users can always run `git submodule update --remote` to get the latest version of the submodules and I don't need to "spam" "update submodule" commits.

I could even update the CMake so it always does the remote update making it transparent for the users.

**Comment by Manu343726** [comment]
Perfect, so if I find a critical bug (Or something on a dependency of interest for cppast) I could just update the submodules and ask you with a PR.

Perfect, thanks for clarifying this for me.
